### ISSUE TITLE
Even easier level - Learning letters?

### ISSUE THREAD

**Issue by mccartney** [selmetwa/parallel-arabic#2]
Context is I am interested to learn Arabic and I was really happy to see your site posted to HN.
Now... I tried that and failed to use it in any meaningful way as even the things labelled as "easy" are hard. I know some letters, but not by heart and even with hints writing is too hard.

How about you add some lesson/section for just memorizing the letters? Their back-and-forth between what you hear and how you type it using Arabic keyboard?

**Comment by selmetwa** [comment]
@mccartney Hey Greg, yeah I think thats a great idea, will definitely add that soon.

**Comment by selmetwa** [comment]
@mccartney Okay I went ahead and added a section of the site for that. 

https://parallel-arabic.com/alphabet

**Comment by mccartney** [comment]
Great stuff. Thanks for doing this. Already using it (a lot to learn:D)
