### ISSUE TITLE
Arabic letters are not connected

### ISSUE THREAD

**Issue by humada05** [selmetwa/parallel-arabic#3]
I tried out the writing section using the provided keyboard and I noticed that the letters were not connected properly when typed. 

This was on mobile btw, not sure if that makes a difference.![image](https://github.com/selmetwa/parallel-arabic/assets/16727862/3aa8c8ce-f8f2-49c3-97d8-84891d374828)

**Comment by selmetwa** [comment]
> I tried out the writing section using the provided keyboard and I noticed that the letters were not connected properly when typed.
> 
> This was on mobile btw, not sure if that makes a difference.![image](https://private-user-images.githubusercontent.com/16727862/322827362-3aa8c8ce-f8f2-49c3-97d8-84891d374828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzU5NDgsIm5iZiI6MTcxMzI3NTY0OCwicGF0aCI6Ii8xNjcyNzg2Mi8zMjI4MjczNjItM2FhOGM4Y2UtZjhmMi00OWMzLTk3ZDgtODQ4OTFkMzc0ODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEzNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYTU0YjE5MzI1YWVkZjdkYThmMGYwMGI0OGVjZmM2ZWNiZmI1NjkwM2E0NzNhYWM3YTU3ODhmM2QxMTFiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v6TPOU4-qy2UsWQc7gVbC8eghONaptsONUSqJnFpsXM)

Ah yeah this seems to be happening on mobile and safari, good catch-- thank you!

**Comment by humada05** [comment]
This might be an old bug with Safari's support of cursive when the letters are wrapped in `<span>` tags: https://w3c.github.io/i18n-tests/results/css-text-shaping#basic_markup

<img width="1363" alt="Screenshot 2024-04-24 at 5 58 21 PM" src="https://github.com/selmetwa/parallel-arabic/assets/16727862/2f8e9056-af66-40ef-82a9-4baa916f7851">

This SO post has a potential workaround where they resolved it using "zero-width characters" but that still didnt work when I tried: https://stackoverflow.com/a/77572225

**Comment by selmetwa** [comment]
> This might be an old bug with Safari's support of cursive when the letters are wrapped in `<span>` tags: https://w3c.github.io/i18n-tests/results/css-text-shaping#basic_markup
> 
> <img alt="Screenshot 2024-04-24 at 5 58 21 PM" width="1363" src="https://private-user-images.githubusercontent.com/16727862/325431996-2f8e9056-af66-40ef-82a9-4baa916f7851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTI5NTQsIm5iZiI6MTcxNDAxMjY1NCwicGF0aCI6Ii8xNjcyNzg2Mi8zMjU0MzE5OTYtMmY4ZTkwNTYtYWY2Ni00MGVmLTgyYTktNGJhYTkxNmY3ODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAyMzczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MmEyOWY2Mjg4YTIwYWIwNjRmZjdmODdmOGJiNWRjZGVjNTA4ZTllZDQ0MTQyMDAyMjcxZWJkYmM0NjUyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WjniXwshAfmOvcknrO3H-4fiHbcPXX7Owinj2Xecgok">
> This SO post has a potential workaround where they resolved it using "zero-width characters" but that still didnt work when I tried: https://stackoverflow.com/a/77572225

After doing some digging I found this SO post: https://stackoverflow.com/questions/11155849/partially-colored-arabic-word-in-html. 

I just pushed up and deployed a fix. Looks like we need to use two `zero-width characters` `&zwj;`. The text looks likes it now connecting as expected on safari web and mobile. Are you still able to reproduce the issue?

<img width="1247" alt="Screenshot 2024-04-24 at 10 59 06 PM" src="https://github.com/selmetwa/parallel-arabic/assets/46908343/1e2cb2fe-f4ce-4cdb-bdd8-a1879ef44426">


```
      <span class='text-[35px]'>
        {@html attempt.map(({ letter, correct }) => 
        `<span class="${cn('text-[35px]', { 'text-green-500': correct, 'text-red-500': !correct })}">&zwj;&zwj;${letter}&zwj;&zwj;</span>`
      ).join('')}
      </span>

**Comment by humada05** [comment]
@selmetwa its working for me now, thanks!
