### ISSUE TITLE
500 Internal Error in profile

### ISSUE THREAD

**Issue by mccartney** [selmetwa/parallel-arabic#5]
This happens deterministically for me
![Screenshot_20240425-231904.jpg](https://github.com/selmetwa/parallel-arabic/assets/762437/034d7456-d94c-4d57-a1d6-f21dfdb2e9d0)

when I visit 
https://parallel-arabic.com/profile

**Comment by selmetwa** [comment]
> This happens deterministically for me ![Screenshot_20240425-231904.jpg](https://private-user-images.githubusercontent.com/762437/325774394-034d7456-d94c-4d57-a1d6-f21dfdb2e9d0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjE1MjcsIm5iZiI6MTcxNDY2MTIyNywicGF0aCI6Ii83NjI0MzcvMzI1Nzc0Mzk0LTAzNGQ3NDU2LWQ5NGMtNGQ1Ny1hMWQ2LWYyMWRmZGIyZTlkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNDQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUyYWQzZjJlNDI5NWE3NTVhMzc4ODc4NGM5NzQ0NGVhNDMyNzY3Yzk4NDdlMWY2OWEyNmYwYmJjMDNmM2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZmH5BrcIPl_shKl6PTm0us-god9ADzy306Tokf1P1ZE)
> 
> when I visit https://parallel-arabic.com/profile

@mccartney Is this still happening for you? I haven't been able to reproduce.

**Comment by selmetwa** [comment]
> > This happens deterministically for me ![Screenshot_20240425-231904.jpg](https://private-user-images.githubusercontent.com/762437/325774394-034d7456-d94c-4d57-a1d6-f21dfdb2e9d0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjE1MjcsIm5iZiI6MTcxNDY2MTIyNywicGF0aCI6Ii83NjI0MzcvMzI1Nzc0Mzk0LTAzNGQ3NDU2LWQ5NGMtNGQ1Ny1hMWQ2LWYyMWRmZGIyZTlkMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNDQ3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGUyYWQzZjJlNDI5NWE3NTVhMzc4ODc4NGM5NzQ0NGVhNDMyNzY3Yzk4NDdlMWY2OWEyNmYwYmJjMDNmM2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZmH5BrcIPl_shKl6PTm0us-god9ADzy306Tokf1P1ZE)
> > when I visit https://parallel-arabic.com/profile
> 
> @mccartney Is this still happening for you? I haven't been able to reproduce.

@mccartney Okay should be fixed, sorry for the delay.
